### ISSUE TITLE
How to use transactions?

### ISSUE THREAD

**Issue by JensWinkler91** [jorasmhj/db-mongo-migration#55]
Is there any possibility to use transactions? I'd like to update all collections or nothing, if an error occurs.

**Comment by saroj-mhj** [comment]
> Is there any possibility to use transactions? I'd like to update all collections or nothing, if an error occurs.

Transaction is used by default, if your migration fails midway the migrations won't be committed at all.

**Comment by JensWinkler91** [comment]
Sorry for the late reply and thanks for your response!
